/*
 * This file is generated by jOOQ.
*/
package database.mysql.model;


import database.mysql.model.tables.Testdata;
import database.mysql.model.tables.records.TestdataRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>test</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TestdataRecord, Integer> IDENTITY_TESTDATA = Identities0.IDENTITY_TESTDATA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TestdataRecord> KEY_TESTDATA_PRIMARY = UniqueKeys0.KEY_TESTDATA_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TestdataRecord, Integer> IDENTITY_TESTDATA = createIdentity(Testdata.TESTDATA, Testdata.TESTDATA.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TestdataRecord> KEY_TESTDATA_PRIMARY = createUniqueKey(Testdata.TESTDATA, "KEY_testData_PRIMARY", Testdata.TESTDATA.ID);
    }
}
