/*
 * This file is generated by jOOQ.
*/
package database.mysql.model;


import database.mysql.model.tables.Testdata;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.testData</code>.
     */
    public static final Testdata TESTDATA = database.mysql.model.tables.Testdata.TESTDATA;
}
